name: Scheduled Health Check

# This workflow triggers on a schedule: every 12 hours (at 00:00 and 12:00 UTC)
on:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Health Check Script
        id: shell_script_run
        run: bash ./health-check.sh
